version: "3.9"

services:
  mariadb:
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    restart: always
    image: mariadb
    container_name: mariadb
    networks:
      - net
    volumes:
      - /home/gkarina/data/mariadb_database:/var/lib/mysql
    expose:
      - ${MYSQL_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
#    healthcheck:
#      test: ["CMD", ]
#      interval: 1s
#      timeout: 10s
#      retries: 10
#      start_period: 15s

  nginx:
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    restart: always
    image: nginx
    container_name: nginx
    networks:
      - net
    ports:
      - ${HOST_PORT_SSL}:${CONTAINER_PORT_SSL}
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      CERTS_PATH: ${CERTS_PATH}
      WORDPRESS_CONTAINER_NAME: ${WORDPRESS_CONTAINER_NAME}
      WORDPRESS_PORT: $WORDPRESS_PORT
    depends_on:
      - mariadb

  wordpress:
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    restart: always
    image: wordpress
    container_name: wordpress
    networks:
      - net
    volumes:
      - /home/gkarina/data/wordpress_database:/var/www/wordpress
    expose:
      - ${WORDPRESS_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_CONTAINER_NAME: ${MYSQL_CONTAINER_NAME}
      MYSQL_PORT: ${MYSQL_PORT}
      WORDPRESS_PORT: ${WORDPRESS_PORT}
      DOMAIN_NAME: ${DOMAIN_NAME}
    depends_on:
      - mariadb

networks:
  net:
    name: netinet

#volumes:
#  mariadb_database:
#    name: mariadb_db
#    driver: local
#    driver_opts:
#      type: nfs
#      o: bind
#      device: ./requirements/tools/mariadb_database
#  wordpress_database:
#    name: wordpress_volume
#    driver: local
#    driver_opts:
#      o: bind
#      type: none
#      device: $PWD/requirements/tools/wordpress_database