version: "3.9"

services:
  mariadb:
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    restart: always
    image: mariadb
    container_name: mariadb
    networks:
      - netinet
    volumes:
      - mariadb_database:/var/lib/mysql
    expose:
      - ${MYSQL_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
#    healthcheck:
#      test: ["CMD", ]
#      interval: 1s
#      timeout: 10s
#      retries: 10
#      start_period: 15s

  nginx:
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    restart: always
    image: nginx
    container_name: nginx
    networks:
      - netinet
    ports:
      - ${HOST_PORT_SSL}:${CONTAINER_PORT_SSL}
    volumes:
      - wordpress_database:/var/www/wordpress
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      CERTS_PATH: ${CERTS_PATH}
      WORDPRESS_CONTAINER_NAME: ${WORDPRESS_CONTAINER_NAME}
      WORDPRESS_PORT: $WORDPRESS_PORT
    depends_on:
      - wordpress

  wordpress:
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    restart: always
    image: wordpress
    container_name: wordpress
    networks:
      - netinet
    volumes:
      - wordpress_database:/var/www/wordpress
    expose:
      - ${WORDPRESS_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_CONTAINER_NAME: ${MYSQL_CONTAINER_NAME}
      MYSQL_PORT: ${MYSQL_PORT}
      WORDPRESS_PORT: ${WORDPRESS_PORT}
      DOMAIN_NAME: ${DOMAIN_NAME}
    depends_on:
      - mariadb

networks:
  netinet:
    name: netinet

volumes:
  mariadb_database:
    name: mariadb_database
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/gkarina/data/mariadb_database
  wordpress_database:
    name: wordpress_database
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/gkarina/data/wordpress_database