version: "3.9"

services:
  mariadb:
    build: ./requirements/mariadb/
    restart: always
    image: mariadb
    container_name: mariadb
    networks:
      - net
    volumes:
      - ./requirements/tools/mariadb_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
  
  # nginx:
  #   build: ./requirements/nginx/
  #   restart: always
  #   image: nginx
  #   container_name: nginx
  #   networks:
  #     - net
  #   ports:
  #     - ${HOST_PORT}:${CONTAINER_PORT}
  #     - ${HOST_PORT_SSL}:${CONTAINER_PORT_SSL}
  #   depends_on:
  #     - mariadb

  # wordpress:
  #   build: ./requirements/wordpress/
  #   restart: always
  #   image: wordpress
  #   container_name: wordpress
  #   networks:
  #     - net
  #   depends_on:
  #     - mariadb
  #   volumes:
  #     - ./requirements/tools/wordpress_database:/var/www/wordpress
  #   environments:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}



# volumes:
  # ./requirements/tools/mariadb_database
  # ./requirements/tools/wordpress_database


networks:
  net:
    name: netinet

