version: "3.7"

services:
  mariadb:
    build: ./requirements/mariadb/
    restart: always
    image: mariadb
    container_name: mariadb
    networks:
      - net
    volumes:
      - ./requirements/mariadb/tools/mysql_volume:/var/lib/mysql
    environments:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
  
  nginx:
    build: ./requirements/nginx/
    restart: always
    image: nginx
    container_name: nginx
    networks:
      - net
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mariadb

  wordpress:
    build: ./requirements/wordpress/
    restart: always
    image: wordpress
    container_name: wordpress
    networks:
      - net
    depends_on:
      - mariadb
    volumes:
      - ./data:/var/www/wordpress
    environments:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}


  # wordpress:
  #   build: $PWD/requirements/wordpress/
  #   # command: /bin/bash -c "/files/wordpress.sh"
  #   ports:
  #     - 9000:9000
  #     - 3306:3306
  #   working_dir: /
  #   restart: always
  #   volumes:
  #     - $PWD/requirements/wordpress/tools/wordpress_volume:/var/www/wordpress/wp-content

# volumes:
  # $PWD/requirements/mariadb/tools/mysql_volume
  # $PWD/requirements/wordpress/tools/wordpress_volume

